### PR TITLE
Allow more than one interface in `World.AddSystemInterface` in and ex.

### PR DESCRIPTION
**Pull request by sbrow**
This PR implements the changes discussed in issue #37.

### CODE REVIEW

**Comment by Noofbiz** [comment]
No worries about the CI issues. I'll fix those and rerun this ^_^ Thanks for the PR!

**Comment by Noofbiz** [comment]
That one looks like an actual fail. Looks like the excluded flags aren't working in some of the tests; it's adding entities to systems even though the entities have the exclude flag.

**Comment by Noofbiz** [comment]
Sorry! I meant to merge this in back then and completely lost track of it!

**Comment by sbrow** [comment]
> Sorry! I meant to merge this in back then and completely lost track of it!

No worries, stuff happens :)

**Pull request merged**
